# App
spring.application.name=multi-currency-api
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb
spring.datasource.username=bankuser
spring.datasource.password=bankpass123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Exchange Rate API (free)
exchange.rate.api.url=https://api.exchangerate-api.com/v4/latest/

# Redis Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=300000

# JWT
jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7a7d2f1f4faed7e0e3a4e36b2
jwt.expiration=86400000
